### ISSUE TITLE
improve payload with typedInput

### ISSUE THREAD

**Issue by Steve-Mcl** [bartbutenaers/node-red-contrib-ui-contextmenu#1]
Bart, I propose the contextmenu to uteilise typedInput and topic - much like the SVG node so that upon a menu item `click`, the `msg` being sent can be what the user wants without having to use a switch and change nodes connected to the output.

As i see it, the list editor would need...
* name - name of the menu item
* label - text to display
* icon - icon
* topic - topic to send on click
* payload - payload to send on click
* enabled - do we need this on static menu? How would we dynamically enable a menu item?
* visible - do we need this on static menu? How would we dynamically show a menu item?

NOTE: 
consideration should be made for nested items on the editor at some point but for first release I propose we support nested menus through `msg` only.

**Comment by bartbutenaers** [comment]
@Steve-Mcl ,
Very reasonable proposal.

The **_enable/visible_** options might be useful in my opinion:  then you can simply configure a FULL menu in the config screen, and hide/disable some of the options via messages (based on their menu name).  This way the users only need to send Booleans via the input message, without having to send an entire json containing the menu structure.  Surely not everybody will use it that way, but I think I would ...

**Comment by Steve-Mcl** [comment]
Done.

For `msg` based menus, the properties `payload`, payloadType` and `topic` can be included.  E.g...

msg.menu = {
            "edit": {"name": "Edit", "icon": "fa-edit", "topic": "edit", "payload": "hello", "payloadType": "str" },
            "cut": {"name": "Cut", "icon": "fa-cut", "topic": "cut", "payload": "1", "payloadType": "num" },
            "timeNow": {"name": "Time", "icon": "fa-clock", "topic": "time", "payloadType": "date" }
}

Supported payloadTypes are 'flow', 'global', 'str', 'num', 'bool', 'json', 'date'
