### ISSUE TITLE
CSS is not applied

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-contextmenu#12]
There is no styling applied to the context menu:

![image](https://user-images.githubusercontent.com/14224149/65723471-c1b05180-e0ae-11e9-9342-6670ba58a0b7.png)

**Comment by bartbutenaers** [comment]
Seems that is the default css setting, which is applied...
Seems there are 3 other styles [available](https://github.com/dsaul/contextmenujs):

![image](https://user-images.githubusercontent.com/14224149/65800342-837e6500-e176-11e9-9377-4c518289a593.png)

@Steve-Mcl : is there any reason why you haven't used one of these availble styles, or is it just something we still need to decide?

**Comment by Steve-Mcl** [comment]
perhaps we could offer users a choice?

if I remember right, the original default was a very grey windows95esc affair and not so pleasant so I tweaked it slightly. if I remember right, I couldn't (at the time) figure out how to apply an alternate style. 

if you think it worth while, then maybe we could add a theme choice to the user?

**Comment by bartbutenaers** [comment]
@Steve-Mcl: we could also show a color picker on the config screen.  Or we can get the colors automatically from the current Node-RED theme.  Or even better: show a dropdown where you can select these both options.

**Comment by Steve-Mcl** [comment]
I did have it in mind to utilise current theme settings from dashboard but I couldn't see how to do that. Do you know how we can pick up dashboard settings and apply them to our HTML?
