### ISSUE TITLE
Add separators on config screen

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-contextmenu#13]
Perhaps we could provide an extra "**Add separator**" button to the editable list ?

**Comment by Steve-Mcl** [comment]
I've documented the creation of separators in the readme and built in help. it is not uncommon for menu libraries to specify the user enters "---" for a separator. this is exactly how I handles it. 

it would ultimately look nicer if there was a dynamic list entry that hid the other fields when a tick box or drop-down specified the entry to be a separator but for now, "---" is a good compromise. (IMHO)

**Comment by bartbutenaers** [comment]
Deal!
