### ISSUE TITLE
Empty space when no label/icon

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-contextmenu#14]
The labels and icons are optional.  But when not specified, an empty place will be displayed:

![image](https://user-images.githubusercontent.com/14224149/65723677-29ff3300-e0af-11e9-8dfa-18a6a904a980.png)

**Comment by Steve-Mcl** [comment]
I think there are 3 options here...

1. Leave as is (perhaps adjust the CSS so the show the vertical line is more prominent e.g...
![example](https://github.com/dsaul/contextmenujs/raw/master/demo/example.gif)
2. Heavy mods to original lib code to remove this space :eek:
3. Default icon - perhaps a bullet? or other???

EDIT...
The library already has a settable option `default_icon` is we choose option 3

**Comment by Steve-Mcl** [comment]
If we are to do option 3 - this works...
https://github.com/bartbutenaers/node-red-contrib-ui-contextmenu/blob/44caad663571a7a5cd92905269e6a6fa158890c5/context_menu.js#L267

**Comment by bartbutenaers** [comment]
@Steve-Mcl  Ok,than we have already at least a backup plan...
But I'm wondering if users would like to display a context menu without labels.
If that is the case, we need to get rid of the empty space...

**Comment by Steve-Mcl** [comment]
I think this is a non-issue TBH bart.

Look at chrome context menu - mostly white-sapce on the lefthand side.  

How I see other menus handling this is to have even whitespace on the right

I'll close for now.  Re-open if you feel strongly enough
