### ISSUE TITLE
No context menu when no labels specified

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-contextmenu#15]
The context menu is not displayed when no labels are specified.  But in some cases it is convenient only to display icons.  Workaround is to add a single whitespace in the label field...

**Comment by Steve-Mcl** [comment]
this could be handled under the the hood (i.e. don't force user to enter a space, but instead, if an entry is blank then ensure it will be displayed by applying some default or handle empty label in a way that negates the user having to enter something). thoughts?
