### ISSUE TITLE
Close contextmenu on timeout

### ISSUE THREAD

**Issue by EvertDekker** [bartbutenaers/node-red-contrib-ui-contextmenu#17]
It would be nice if there was an timeout on the contextmenu, or other way to close it.
If you don't choose something now from the menu it will stay visible  for ever.
Or better an input msg like msg.close that you can control yourself with a timer node.

**Comment by bartbutenaers** [comment]
Morning Evert,
Sorry, have somehow missed your question.  Good idea!!  Will have implement it at it as soon as possible.

**Comment by bartbutenaers** [comment]
Evert,
Version 1.0.2 is available on Github with the auto-hide feature.  
You can find demo and explanation on the readme page.
Please close this issue if the implementation fits your needs...
And keep the good ideas coming ;-)
Bart
