### ISSUE TITLE
Context menu takes 4x3 space in dashboard

### ISSUE THREAD

**Issue by EvertDekker** [bartbutenaers/node-red-contrib-ui-contextmenu#21]
I'm notice that I have on my tablet a scrollbar at the right of my svg floorplan, this is not ideal.
At the bottom of my floorplan there's a empty area that causes the appears of the scrollbar.
After some testing I found out the this is coming from the context menu.
The context menu takes up 4x3 invisible space in the dashboard.
Why is this? can't it be 1x1 or even better 0x0 ?

![Contextmenuspace](https://user-images.githubusercontent.com/5690965/71494070-8277d500-2844-11ea-8ef1-6e65dc27ef35.png)

![Contextmenuspace2](https://user-images.githubusercontent.com/5690965/71494246-ea7aeb00-2845-11ea-9814-9c9d41058d3b.png)

**Comment by bartbutenaers** [comment]
Hi Evert,
Could the problem perhaps be related to this [discussion](https://discourse.nodered.org/t/custom-dashboard-node-without-md-card-possible/14919/20?u=bartbutenaers).  You need to have at least dashboard version **2.16.3**.
Bart

**Comment by EvertDekker** [comment]
Hi Bart,
Thanks for the quick reply, glad to here you guys already solved the problem. And that is should work.
Strange, I have node-red-dashboard 2.19.3.
However I'm still running nr v0.19.5 on my win10 test machine.
Will update this and/or try it on my raspberry.

to be continued..

**Comment by EvertDekker** [comment]
It working now after updating NR to 1.0.3. 
No empty area visible any more under the floorplan and therefore the scrollbar is also gone.

Thanks again for pointing me in the right direction.

**Comment by bartbutenaers** [comment]
Thanks for sharing the result!
I have published a new minor version (**1.0.6**) on NPM, to mention this on the readme page:

![image](https://user-images.githubusercontent.com/14224149/71531448-fb336b80-28ee-11ea-86ea-2a813bee7ae1.png)

Did the same thing a few weeks ago on the readme file of the SVG node, but completely forgot to add it for the contextmenu node...
