### ISSUE TITLE
menu adjustment at perimeter

### ISSUE THREAD

**Issue by greenembrace** [bartbutenaers/node-red-contrib-ui-contextmenu#24]
1. sub-menu at the lower perimeter of canvas extends beyond the lower bound. If window is sized to the actual size of the canvas, access to the lower items is lost. 

![image](https://user-images.githubusercontent.com/6187573/77268406-e30a9700-6cf9-11ea-9135-bfed4c1d458e.png)

2. sub-menu at right perimeter unfolds correctly to the left but there is a break between the lists, that appears to increase with additional sub-menus.

![image](https://user-images.githubusercontent.com/6187573/77268511-4d233c00-6cfa-11ea-9d62-469825a1bc0a.png)

**Comment by Steve-Mcl** [comment]
Hi, I have been working on context menu positioning - see gif...

![new_cm_positioning](https://user-images.githubusercontent.com/44235289/80862926-9c04af80-8c70-11ea-832c-0599cb2f0ab6.gif)

If you are willing to test, please install from github like this...

1. CD to node red folder (usually `~/.node-red` or `%userprofile%\.node-red`)
1. uninstall npm version
   1. npm u node-red-contrib-ui-contextmenu
1. install github version
   1. npm install bartbutenaers/node-red-contrib-ui-contextmenu#new_layout_calcs 
1. restart node-red

**Comment by greenembrace** [comment]
This issue was solved with steve-mcl last changes. many thanks

**Comment by Steve-Mcl** [comment]
published changes in v1.0.13
