### ISSUE TITLE
Payload not number when set in fixed menu

### ISSUE THREAD

**Issue by EvertDekker** [bartbutenaers/node-red-contrib-ui-contextmenu#27]
When you set in the fixed menu the payload should be a number, the output is a string.

![Contextmenu](https://user-images.githubusercontent.com/5690965/83301486-0a9a4600-a1fa-11ea-861d-9b6581ceece2.PNG)

When you set the context menu with a message it works fine.

Context menu 1.0.13

**Comment by bartbutenaers** [comment]
Hi Evert (@EvertDekker),
Thanks for reporting this issue.
I have published version 1.0.14 which should fix this problem.
Feel free to reopen this issue when you still have problems.
Bart
