### ISSUE TITLE
Sub menu on touch devices

### ISSUE THREAD

**Issue by andreypopov** [bartbutenaers/node-red-contrib-ui-contextmenu#28]
Disappears so fast, impossible to tap on sub menu item. Ideas?

**Comment by bartbutenaers** [comment]
Hi Andrey,
Doesn't the "auto hide" property work correctly on your device?
Bart

**Comment by andreypopov** [comment]
Auto hide doesn't affect submenu. On touch devices there is no focus so submenu disappears

**Comment by bartbutenaers** [comment]
I have updated the version on Github (not on npm!), where I use now [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events):

![image](https://user-images.githubusercontent.com/14224149/92205499-1a26cc00-ee86-11ea-9ecc-f94f24e5d350.png)

Those events respond both to mouse and to touch...
Can this solve your problem?

I had set the auto hide time on 5 seconds, and after 5 seconds the menu disappears on my Android phone...

**Comment by andreypopov** [comment]
no, still doesn't work, I can try to search solution later

**Comment by bartbutenaers** [comment]
Andrey,
do you have any extra information for me to solve this?
+ On which kind of device it is.  I only can test on Android devices.
+ What exactly happens?  So the menu appears correctly, but when you open a submenu then it immediately disappears?  And you keep pressing the screen, or you move up your finger in between, or ...

**Comment by andreypopov** [comment]
Raspberry + Touch monitor

Video:
https://www.dropbox.com/s/81rjum68mx7fgec/IMG_6251.MOV?dl=0

**Comment by bartbutenaers** [comment]
Andrey,
To be able to solve this, I have setup a fresh Raspbian system with user interface.
But when I test this (with auto hide set to 5 seconds), this works fine on an ***official Raspberry touch screen*** (connect to the RPI):

![raspberry_touch](https://user-images.githubusercontent.com/14224149/92467458-f212d200-f1d1-11ea-9b90-fd6152b5a2f8.gif)

Behaves exactly the same as on Android touch screens...

So I'm afraid I need your (debugging) help if you want to get this solved...

**Comment by andreypopov** [comment]
My touch monitor on linux emulates touch as click, so there is no **hover** state. The issue is in menu plugin. I made quick fix for my screen:

```
.cm_container li > ul{
   transition: 0s; 
}
.cm_container li.hovered > ul{
   opacity: 1;
   visibility: visible;
   transition-delay: 0s; 
}
.cm_container li.hovered{
   background-color:#000066;
}
```
```
$(function(){
            $('.fixedmenu').on('click', function(){
                setTimeout(function(e){
                    $('.cm_container li').off('click').on('click', function(e){
                        var $parent = $(this).closest('li.hovered');
                        console.log($(this).find('.hovered').length);
                        if ($(this).find('.hovered').length) {
                            e.preventDefault();
                            return false;
                        }
                        $('.cm_container li.hovered').not($parent).removeClass('hovered');
                        $(this).addClass("hovered");
                    });
                }, 200);
            });
});
```

**Comment by bartbutenaers** [comment]
Hi @andreypopov,
Thanks for the investigation!
Is this fix something you do in your in your local version, or do you want it to be integrated into this repository?

**Comment by andreypopov** [comment]
it is workaround in my flow
contextmenu.js needs global changes to implement this
