### ISSUE TITLE
ability to add separator items

### ISSUE THREAD

**Issue by Steve-Mcl** [bartbutenaers/node-red-contrib-ui-contextmenu#3]
The context menu should be able to have separators.

**Comment by bartbutenaers** [comment]
@Steve-Mcl ,
Separators are indeed much cleaner.  Perhaps make this adjustable (show/hide) via a checkbox in the config screen?  Because I can imagine that some users only want to display icons (so no labels), and then perhaps they don’t want separators ...

**Comment by Steve-Mcl** [comment]
Done.

Set item text to "---" to create a separator
