### ISSUE TITLE
DIV present in dashboard & widget visible in layout 

### ISSUE THREAD

**Issue by Steve-Mcl** [bartbutenaers/node-red-contrib-ui-contextmenu#5]
Ideally this widget is just adding a comtext menu to the dom - we dont want an md- card displayed in the dashboard (even if it is empty - its still taking up space) nor do we really want it to apear in the dashboard layout but we do want to specify which page/tab (I think!)

Perhaps dashboard supports zero height and width ui widgets?

We may need to ask dev!

**Comment by bartbutenaers** [comment]
@Steve-Mcl 
We will indeed have to ask this on the forum ...

**Comment by Steve-Mcl** [comment]
@bartbutenaers could I ask (beg) you to ask this on the forum please?

I see the ui_template node has an option to "add to head" that removes if from the layout editor. Under the hood, this sets `templateScope = 'global'` 

I have tried setting "templateScope" to "global" but it puts HTML into head and removes it from the layout editor (to be expected) however I suspect the mechanism that transmits messages is removed.

I suppose we need a kinda "add to body" `templateScope = 'body' whereby the msg exchange is still possible but no md-card is generated (perhaps a 0 width div that doesnt take space on the dashboard.

Cheers.

**Comment by bartbutenaers** [comment]
We should now only mention in the readme page that this is [solved ](https://discourse.nodered.org/t/custom-dashboard-node-without-md-card-possible/14919/20)in dashboard 2.16.3.
