### ISSUE TITLE
Contextmenu reappears after deploy

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-contextmenu#9]
When the browser page is refreshed, the previous context menu is again showed.

After refresh:
+ In the initController function, the context menu isn't available yet.
+ But then the last input message is again loaded.
+ As a result the context menu is again build and showed.

Have tested this [suggestion ](https://discourse.nodered.org/t/refresh-ui-node/13921/8?u=bartbutenaers)from Dave, but it doesn't help...

**Comment by Steve-Mcl** [comment]
Not certain I understand the reason for resending last message.  In our case its really unwanted.

The comment above daves says...

> This is about same problem as in this thread API addwidget()
Conclusion is - On redeploy/refresh the API resend last incoming payload.
As you can't change this behavior, you should respect it and build your widget to follow the underlying logic.

So unless we ask Dave for a workaround or solution, we might have to somehow handle this (though I'm not certain how.

Do we ignore any msg for xxxxms after creation?

Do we ignore 1st msg after node init?

Is there a flag in the msg to state this is a re-send?

**Comment by bartbutenaers** [comment]
Indeed this really unwanted in our case.   The flag in the message could indeed be a workaround (if it works ...).

**Comment by bartbutenaers** [comment]
I have changed the title from "refresh" to "deploy", since I can only reproduce it by deploying:

1. Make sure a context menu is displayed:
   
   ![image](https://user-images.githubusercontent.com/14224149/65839808-1fdc6f00-e311-11e9-8875-a8ca21488318.png)

2. Then change something in the flow and deploy.

3. The message will be replayed already during loading of the dashboard:
   
   ![image](https://user-images.githubusercontent.com/14224149/65839833-531efe00-e311-11e9-8a9c-34434202e321.png)

4. So the contextmenu will again be available at the same position (like in the screenshot of step 1).

**Comment by bartbutenaers** [comment]
Same [discussion ](https://discourse.nodered.org/t/refresh-ui-node/13921/14)as for our SVG node.  So solution will be the same.

**Comment by andreypopov** [comment]
any news here? I have annoying menus after deploy too

**Comment by bartbutenaers** [comment]
Hi Andrey,
At the time being we have added a workaround, so we thought this would have been solved...
Can you give some more information.
+ Does it do that after every deploy, or from time to time?
+ Could it be that you have a slow connection perhaps?  Because the workaround is time based...
+ Other circumstances?

I think I saw last week a related pull request on the dashboard repository.  Will need to have a look at that as soon as I have time.
Bart

**Comment by andreypopov** [comment]
Almost every deploy, I have 15+ content menus, every time different menus.
![2020-02-13_09-27-11](https://user-images.githubusercontent.com/1624839/74407520-35c37a00-4e43-11ea-8785-11d3dfc898c1.png)

On page refresh:
![2020-02-13_09-29-34](https://user-images.githubusercontent.com/1624839/74407615-62779180-4e43-11ea-87f1-2697c2c0da06.png)

**Comment by andreypopov** [comment]
and try "deploy only modified"
![2020-02-13_09-30-41](https://user-images.githubusercontent.com/1624839/74407721-a8ccf080-4e43-11ea-8d55-e20b8862a8fa.png)

**Comment by bartbutenaers** [comment]
Thanks for the feedback!  That is indeed a VERY annoying problem.  Will ask today on the forum more information about the pull request

**Comment by bartbutenaers** [comment]
I have asked it on the Discourse forum (see [here](https://discourse.nodered.org/t/announce-dashboard-version-2-19-0-1-2-3-4/18502/6?u=bartbutenaers)), so hopefully we get an answer soon...

**Comment by bartbutenaers** [comment]
Andrey,
Could you please install my latest version (**1.0.8**) from Github (not on npm yet!) to test whether it is fixed?  You can install it like this, from your Node-RED folder:
```
npm install bartbutenaers/node-red-contrib-ui-contextmenu
```
And make sure your have dashboard version **2.19.4** and refresh your browser screen!

**Comment by andreypopov** [comment]
Wow, now I dont see this bug, tried on 3 different screens!  great job! I will test it next few days.

**Comment by bartbutenaers** [comment]
Nice to have so quick feedback.  Then I assume it will keep working fine.  I will publish it anyway on npm for other users.  But please let me know in a couple of days how it went, and then I will close this issue...

**Comment by bartbutenaers** [comment]
You can now install it also via the Node-RED menu:

![image](https://user-images.githubusercontent.com/14224149/74480452-35fa5e80-4eb1-11ea-9beb-8472086b2192.png)

**Comment by andreypopov** [comment]
everything is perfect now! you can close this issue
thank you

**Comment by bartbutenaers** [comment]
Have fun with it Andrey!!
